version: education_prompt_v1

task:
  task1: |
    Evaluate <section_name> section with <targetrole> role

expected_content:
  Education: |
    - point A
    - point B
    - point C
    
criteria:
  Completeness:
    score5: |
      - Education.Completeness.score5
      - Example
        - Education.Completeness.example      
    score3: |
      - Education.Completeness.score3
      - Example
        - Education.Completeness.example
    score1: |
      - Education.Completeness.score1
      - Example
        - Education.Completeness.example
  RoleRelevance:
    score5: |
      - Education.RoleRelevance.score5
      - Example
        - Education.RoleRelevance.example      
    score3: |
      - Education.RoleRelevance.score3
      - Example
        - Education.RoleRelevance.example
    score1: |
      - Education.RoleRelevance.score1
      - Example
        - Education.RoleRelevance.example


output_guidelines:
  Education: |
    - Completeness:
      - score_5 : output_guidelines.Summary.Completeness.guideline
      - score_3 : output_guidelines.Summary.Completeness.guideline
      - score_1 : output_guidelines.Summary.Completeness.guideline
    - RoleRelevance:
      - score_5 : output_guidelines.Summary.Completeness.guideline
      - score_3 : output_guidelines.Summary.Completeness.guideline
      - score_1 : output_guidelines.Summary.Completeness.guideline