version: global_v1
setting:
  GOOGLE_API_KEY: AIza-xxxx
pricing:
  gemini_2_5_flash:
    input_per_million: 0.30
    output_per_million: 2.50
scoring:
  final_score_max: 100               # plan to use in the future
  normalize: true                    # plan to use in the future
  round_digits: 2                    # plan to use in the future
  aggregation_method: weighted_sum   # plan to use in the future
currency:
  USD_to_THB : 31.42                 # 1 USD = 31.42 Baht 251221.12:24 
logging:
  logging_round_digit : 5            # rounding time before keep in log
feedback:
  session_feedback_word : 20         # promptbuilder.py limit session_feedback_words
output:
  number_of_words : 20               # Number of word use with promputbuilder.py