version: global_v1
setting:
  GOOGLE_API_KEY: AIza-xxxx
pricing:
  gemini_2_5_flash:
    input_per_million: 0.30
    output_per_million: 2.50
scoring:
  final_score_max: 100
  normalize: true
  round_digits: 2
  aggregation_method: weighted_sum
currency:
  USD_to_THB : 31.42                 # 1 USD = 31.42 Baht 251221.12:24 
logging:
  logging_round_digit : 5

