version: weights_v1
weights:
    Profile:
        Completeness: 10
        ContentQuality: 10
        Grammar: 0
        Length: 0
        RoleRelevance: 0
        section_weight: 0.1
    Summary:
        Completeness: 10
        ContentQuality: 10
        Grammar: 10
        Length: 10
        RoleRelevance: 10
        section_weight: 0.1
    Education:
        Completeness: 10
        ContentQuality: 0
        Grammar: 0
        Length: 0
        RoleRelevance: 10
        section_weight: 0.2
    Experience:
        Completeness: 10
        ContentQuality: 10
        Grammar: 10
        Length: 10
        RoleRelevance: 10
        section_weight: 0.2
    Activities:
        Completeness: 10
        ContentQuality: 10
        Grammar: 10
        Length: 10
        RoleRelevance: 10
        section_weight: 0.2
    Skills:
        Completeness: 10
        ContentQuality: 0
        Grammar: 0
        Length: 10
        RoleRelevance: 10
        section_weight: 0.2
